-- =========================================================
-- DASH IMOVEIS OLX - SETUP AUTENTICAÇÃO POR USUÁRIO
-- =========================================================

-- Tabelas base
create table if not exists public.imoveis (
  id bigint generated by default as identity primary key,
  user_id uuid,
  nome text,
  preco text,
  preco_num numeric,
  preco_m2 numeric,
  m2 numeric,
  cidade text,
  bairro text,
  estado text,
  link text,
  fonte text,
  criado_em timestamptz not null default now()
);

create table if not exists public.imoveis_historico (
  id bigint generated by default as identity primary key,
  user_id uuid,
  nome text,
  preco text,
  preco_num numeric,
  preco_m2 numeric,
  m2 numeric,
  cidade text,
  bairro text,
  estado text,
  link text,
  fonte text,
  criado_em timestamptz not null default now()
);

create table if not exists public.pesquisas (
  id bigint generated by default as identity primary key,
  user_id uuid,
  estado text,
  qtd_anuncios integer,
  mediana_preco_m2 numeric,
  mediana_preco_total numeric,
  criado_em timestamptz not null default now()
);

-- Ajustes de ownership para instalações já existentes
alter table public.imoveis add column if not exists user_id uuid;
alter table public.imoveis_historico add column if not exists user_id uuid;
alter table public.pesquisas add column if not exists user_id uuid;

alter table public.imoveis alter column user_id set default auth.uid();
alter table public.imoveis_historico alter column user_id set default auth.uid();
alter table public.pesquisas alter column user_id set default auth.uid();

-- Índices
create index if not exists idx_imoveis_user_estado on public.imoveis (user_id, estado);
create index if not exists idx_imoveis_historico_user_estado on public.imoveis_historico (user_id, estado);
create index if not exists idx_pesquisas_user_criado_em on public.pesquisas (user_id, criado_em desc);

-- RLS
alter table public.imoveis enable row level security;
alter table public.imoveis_historico enable row level security;
alter table public.pesquisas enable row level security;

-- Policies: cada usuário enxerga e altera apenas os próprios dados
drop policy if exists "Users can read own imoveis" on public.imoveis;
create policy "Users can read own imoveis"
on public.imoveis
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can insert own imoveis" on public.imoveis;
create policy "Users can insert own imoveis"
on public.imoveis
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own imoveis" on public.imoveis;
create policy "Users can update own imoveis"
on public.imoveis
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can read own imoveis_historico" on public.imoveis_historico;
create policy "Users can read own imoveis_historico"
on public.imoveis_historico
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can insert own imoveis_historico" on public.imoveis_historico;
create policy "Users can insert own imoveis_historico"
on public.imoveis_historico
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own imoveis_historico" on public.imoveis_historico;
create policy "Users can update own imoveis_historico"
on public.imoveis_historico
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can read own pesquisas" on public.pesquisas;
create policy "Users can read own pesquisas"
on public.pesquisas
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can insert own pesquisas" on public.pesquisas;
create policy "Users can insert own pesquisas"
on public.pesquisas
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own pesquisas" on public.pesquisas;
create policy "Users can update own pesquisas"
on public.pesquisas
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());
